# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

default: &default
  END_POINT: "http://192.168.88.48/"
  API_HOST: "http://192.168.88.48/v1"
  REDIS_HOST: localhost
  REDIS_PORT: 6379
  REDIS_SESSION_DB: 1
  REDIS_SESSION_CHANNEL: session_db
  REDIS_CACHE_DB: 2
  REDIS_SESSION_CHANNEL: cache_db


production:
  <<: *default
development:
  END_POINT: "http://localhost:9292/"
  API_HOST: "http://localhost:9292/v1"
  REDIS_HOST: localhost
  REDIS_PORT: 6379
  REDIS_SESSION_DB: 1
  REDIS_SESSION_CHANNEL: session_db
  REDIS_CACHE_DB: 2
  REDIS_SESSION_CHANNEL: cache_db
test:
  <<: *default
